- name: adding system services
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"
    remote_src: yes
  
- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: starting the services
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
